- name: First interaction
  uses: actions/first-interaction@v1.1.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: You submitted your first issue :raising_hand:! Keep on keeping on :raised_hands::computer:
    # Comment to post on an individual's first pull request
    pr-message: You submitted your first pull request! Awesome work :sunglasses:
